export const GET_FILMS = 'GET_FILMS'
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
export const GET_FILMS_FAILED = 'GET_FILMS_FAILED'

export const GET_INFO_FILMS = 'GET_INFO_FILMS'
export const GET_INFO_FILMS_SUCCESS = 'GET_INFO_FILMS_SUCCESS'
export const GET_INFO_FILMS_FAILED = 'GET_INFO_FILMS_FAILED'

export const GET_EPISODE = 'GET_EPISODE'
export const GET_EPISODE_SUCCESS = 'GET_EPISODE_SUCCESS'
export const GET_EPISODE_FAILED = 'GET_EPISODE_FAILED'

export const GET_HDO_FILMS = 'GET_HDO_FILMS'
export const GET_HDO_FILMS_SUCCESS = 'GET_HDO_FILMS_SUCCESS'
export const GET_HDO_FILMS_FAILED = 'GET_HDO_FILMS_FAILED'

export const GET_PM_FILMS = 'GET_PM_FILMS'
export const GET_PM_FILMS_SUCCESS = 'GET_PM_FILMS_SUCCESS'
export const GET_PM_FILMS_FAILED = 'GET_PM_FILMS_FAILED'

export const GET_BL_FILMS = 'GET_BL_FILMS'
export const GET_BL_FILMS_SUCCESS = 'GET_BL_FILMS_SUCCESS'
export const GET_BL_FILMS_FAILED = 'GET_BL_FILMS_FAILED'

export const GET_PBH_FILMS = 'GET_PBH_FILMS'
export const GET_PBH_FILMS_SUCCESS = 'GET_PBH_FILMS_SUCCESS'
export const GET_PBH_FILMS_FAILED = 'GET_PBH_FILMS_FAILED'

export const GET_P14_FILMS = 'GET_P14_FILMS'
export const GET_P14_FILMS_SUCCESS = 'GET_P14_FILMS_SUCCESS'
export const GET_P14_FILMS_FAILED = 'GET_P14_FILMS_FAILED'

export const GET_XPHIM_FILMS = 'GET_XPHIM_FILMS'
export const GET_XPHIM_FILMS_SUCCESS = 'GET_XPHIM_FILMS_SUCCESS'
export const GET_XPHIM_FILMS_FAILED = 'GET_XPHIM_FILMS_FAILED'

export const GET_FSHARE_FILMS = 'GET_FSHARE_FILMS'
export const GET_FSHARE_FILMS_SUCCESS = 'GET_FSHARE_FILMS_SUCCESS'
export const GET_FSHARE_FILMS_FAILED = 'GET_FSHARE_FILMS_FAILED'

export const GET_INFO_FSHARE_FILM = 'GET_INFO_FSHARE_FILM'
export const GET_INFO_FSHARE_FILM_SUCCESS = 'GET_INFO_FSHARE_FILM_SUCCESS'
export const GET_INFO_FSHARE_FILM_FAILED = 'GET_INFO_FSHARE_FILM_FAILED'

export const SET_MOVIE_SELECTED = 'SET_MOVIE_SELECTED'

export const BOOK_MARK = 'BOOK_MARK'